### PR TITLE
Add .luacheckrc and github workflow

### PR DESCRIPTION
**Pull request by fgaz**
Add [luacheck](https://luacheck.readthedocs.io/) configuration.

This would have caught #59 and #62.

There are a lot of warnings from many of the included mods, so I disabled style warnings and other warnings that I think are not too problematic. Fixing those would make Asuna diverge from upstream mods and would make updating them more difficult.

There are still about ~100 warnings left, and many of them look like actual bugs, for example:

* misspellings such as `minetests`
* missing `local`
* calls to undefined `coral_on_place`
* `seed` overwritten before being used (and therefore discarded) in `too_many_stones` and others

I also added github workflows to automatically check prs, but I'm not sure if they work, testing them is a pain

### CODE REVIEW

**Comment by EmptyStar** [comment]
Neato. This seems like a pretty useful feature for this project. I'll take a closer look when I get some time to spare.

**Comment by EmptyStar** [comment]
I haven't forgotten about this, but I wasn't prepared to leverage it for my latest changes. Improved code organization and quality are on my todo list, so I definitely want to look at this for the future.

**Comment by fgaz** [comment]
As expected the github workflow didn't work. I debugged it on my fork and now it's fixed

**Comment by EmptyStar** [comment]
This looks really good, very thorough and conscious of all of the individual mods and quirky edge cases resulting from Asuna's mod soup approach. I feel like this project will benefit from these checks. I'll approve and merge.

Thank you so much!

**Review by EmptyStar — APPROVED** [review]
Looks great! :+1:

**Pull request merged**
